### ISSUE TITLE
create partitions for past 1 year in pg 10/11

### ISSUE THREAD

**Issue by pavangit1990** [derkan/pg_party#4]
Hi Derkan,

need urgent help for migrating non partition table to partition table. this table as 1 year old data .

I created a new table but for coping data from old to new table, it needs partitions for past 1 year. Can u help me to create older partitions using script in single shot ?

**Comment by pavangit1990** [comment]
any update

**Comment by derkan** [comment]
sorry didn't noticed your first message.

I committed a new release with negative future partition count.

Please update your pg_party and  set `future_part_count` in `pg_party_config` to a negative value(for example **-12**). And run script again.

Note to let script to update db functions, please first drop `pg_party_date_partition` and `pg_party_date_partition_native` functions. When script is run, it will create them again.

**Please do not forget to change  `future_part_count` to a positive value later.**

**Comment by pavangit1990** [comment]
its working.

pg_party_config_ddl not created on pg 11. need it for creating triggers on partitions.

**Comment by pavangit1990** [comment]
please update script to create table g_party_config_ddl for pg 11 version too

**Comment by pavangit1990** [comment]
Any update please

**Comment by derkan** [comment]
added support for 11, thanks.
